- integrations/slack.rb
- spec/integrations/slack_spec.rb
- spec/spec_helper.rb
There are probably a bunch of things we can do to make the integrations
more useful, but this is a start.
@rainforestapp/devs
> Add color to Slack messages

- integrations/slack.rb
- spec/integrations/slack_spec.rb
> Add time to complete on slack message

- config/environments/production.rb
@rainforestapp/customer-product
> force SSL in prod

- lib/integrations/slack.rb
- spec/lib/integrations/slack_spec.rb
> use "danger" color when the run failed

- Gemfile
- app/controllers/events_controller.rb
- spec/controllers/events_controller_spec.rb
> more developer friendly

- fixtures/vcr_cassettes/generic_slack_notification.yml
- lib/integrations/slack.rb
- spec/lib/integrations/slack_spec.rb
> Add time to finish for Slack

- config/routes.rb
- data/events.yml
- data/integrations.yml
- lib/integrations/formatter.rb
- lib/integrations/hip_chat.rb
- lib/integrations/jira.rb
- lib/integrations/pivotal_tracker.rb
- lib/integrations/slack.rb
- spec/lib/integrations/hip_chat_spec.rb
- spec/lib/integrations/pivotal_tracker_spec.rb
- spec/lib/integrations/slack_spec.rb
- spec/models/integration_spec.rb
Fixes #29 
Some changes were made to Rainforest so just making those changes reflected here as well.
> Match json from main app

- integrations/slack.rb
- spec/integrations/slack_spec.rb
> Hotfix2: Do not assume slack 404 is inactive webhooks

- integrations/slack.rb
- lib/rainforest/integrations/html_renderer.rb
- spec/integrations/slack_spec.rb
There were some recent changes to the gem that need to be saved on the appropriate branch before we merge v2 to master.
> Update old gem

- lib/integrations/jira.rb
- lib/integrations/message_formatter.rb
- lib/integrations/slack.rb
- spec/lib/integrations/jira_spec.rb
- spec/lib/integrations/slack_spec.rb
> Check for existing issues in Jira

- .env
- Gemfile
- Gemfile.lock
- app/controllers/application_controller.rb
- app/controllers/integrations_controller.rb
- app/controllers/oauth_controller.rb
- config/application.rb
- config/routes.rb
- data/integrations.yml
- spec/controllers/oauth_controller_spec.rb
Going to have this application doing the heavy lifting with OAuth authentication and letting the frontend get the schema directly from this app (rather than be redirected in the server).
> [WIP] Open API to frontend

- Gemfile
- Gemfile.lock
- app/models/integration.rb
- lib/integrations/base.rb
- lib/integrations/hip_chat.rb
- lib/integrations/slack.rb
- spec/lib/integrations/hip_chat_spec.rb
- spec/lib/integrations/slack_spec.rb
> Rerelease: HipChat

- lib/integrations/jira.rb
- lib/integrations/pivotal_tracker.rb
- spec/lib/integrations/jira_spec.rb
- spec/lib/integrations/pivotal_tracker_spec.rb
> Hotifx: Add final state for pivotal and fix supported event arrays

- lib/integrations/oauth.rb
- spec/lib/integrations/oauth_spec.rb
> Validate OAuth settings

- lib/integrations.rb
- lib/integrations/base.rb
- lib/integrations/settings.rb
- spec/lib/integrations/base_spec.rb
- spec/lib/integrations/settings_spec.rb
- spec/lib/integrations/slack_spec.rb
- spec/lib/integrations_spec.rb
> Validate that required settings are present

- lib/integrations/jira.rb
- spec/lib/integrations/jira_spec.rb
> Move environment to Jira issue description

- lib/integrations/base.rb
- lib/integrations/jira.rb
- spec/lib/integrations/jira_spec.rb
part of #88 
Also stops updating existing issues. It just opens the door to more configuration issues in Jira. The updates did not add any meaningful information anyway.
> Jira error logging and simplification

- lib/integrations/hip_chat.rb
- lib/integrations/jira.rb
- lib/integrations/pivotal_tracker.rb
- spec/lib/integrations/hip_chat_spec.rb
- spec/lib/integrations/jira_spec.rb
- spec/lib/integrations/pivotal_tracker_spec.rb
Basically, do not try to send_event if some crucial pieces of
information are missing.
> Adds a few more checks to #send_event

- data/events.yml
- data/integrations.yml
- fixtures/vcr_cassettes/hipchat_notification_integration_test.yml
- lib/integrations/hip_chat.rb
- lib/integrations/jira.rb
- lib/integrations/pivotal_tracker.rb
- lib/integrations/slack.rb
- spec/lib/integrations/hip_chat_spec.rb
- spec/lib/integrations/jira_spec.rb
- spec/lib/integrations/pivotal_tracker_spec.rb
- spec/lib/integrations/slack_spec.rb
https://paper.dropbox.com/doc/Product-Narrative-Testing-integrations-B3AMN1Os0nGSzG6dFI4L5
> [Rewiew] Add test integrations

- lib/integrations/hip_chat.rb
> hardcoded default url
